In [111]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import os

pd.set_option('display.max_columns', None)

In [112]:
base_path = Path().resolve().parent
file_path = base_path / "current_raw_data" / "combined_data.csv"

df = pd.read_csv(file_path)

In [113]:
df.head()

,Item_ID,Master_Restaurant_Id,Date_ID,Time of Order,Order Delivered Date,Time of Delivery,Expected Delivery Time,Delivery Time (in mins),Restaurant_ID,Desc_ID,Location_ID,Avg Rating_ID,Type_ID,Category_ID,Cuisine_ID,Working Hrs,Delivery Available,Table Booking Available,Price,Discounts Offered (%),Discounted Price,Expected Revenue,Customer ID,Cust Rating_ID,Order_Status_ID,Cancellation_ID,Actual Revenue,Operating Cost,GP Margin,Total Number of Reviews,Number of Complaints Received,Foot Traffic in Location,Competitors in the Area (Count),Subscription_ID,Budgetd_Rev,Budgetd_Operating Cost,Budgeted Order,Budgeted GP,Acquisition cost,Value,year,month
0,7,14,732,5:16:00,2022-01-01,19:13:00,30,26,34,927,8,4,2,4,8,12:00PM - 2:00AM,YES,No,945.41,10.10,849.92,849.92,3353,4,999,5,849.92,626.00,223.92,442,13,high,22,3,893.62,590.80,349.0,261.55,24.79,1073.84,2022,1
1,6,70,732,8:02:00,2022-01-01,9:00:00,49,58,78,956,1,2,1,8,5,11:00AM - 11:00PM,YES,YES,1055.34,12.95,918.67,918.67,3029,1,999,4,0.00,596.63,322.04,23,11,low,6,3,908.62,650.31,187.0,258.31,14.30,349.29,2022,1
2,7,17,732,20:34:00,2022-01-01,4:19:00,40,39,20,914,10,4,2,1,3,10:00AM - 10:00PM,No,YES,633.56,15.95,532.51,532.51,3506,4,999,5,532.51,284.83,247.68,100,10,medium,19,1,559.51,284.43,217.0,289.79,13.62,780.19,2022,1
3,6,64,732,5:46:00,2022-01-01,6:40:00,51,54,36,948,16,4,1,3,2,11:00AM - 11:00PM,YES,YES,1192.89,11.31,1057.97,1057.97,861,5,999,5,1057.97,842.00,215.97,46,15,medium,17,1,1116.96,828.12,291.0,288.84,21.70,253.64,2022,1
4,6,68,732,7:24:00,2022-01-01,8:16:00,47,52,74,938,5,1,1,6,10,11:00AM - 11:00PM,YES,YES,592.40,22.44,459.47,459.47,3144,4,999,3,0.00,341.39,118.08,197,12,high,15,1,467.62,355.01,275.0,112.61,10.09,217.00,2022,1

In [114]:
df.shape

(921, 42)

# **Data Cleaning**

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 921 entries, 0 to 920
Data columns (total 42 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Item_ID                          921 non-null    int64
 1   Master_Restaurant_Id             921 non-null    int64
 2   Date_ID                          921 non-null    int64
 3   Time of Order                    921 non-null    object
 4   Order Delivered Date             921 non-null    object
 5   Time of Delivery                 921 non-null    object
 6   Expected Delivery Time           921 non-null    int64
 7   Delivery Time (in mins)          921 non-null    int64
 8   Restaurant_ID                    921 non-null    int64
 9   Desc_ID                          921 non-null    int64
 10  Location_ID                      921 non-null    int64
 11  Avg Rating_ID                    921 non-null    int64
 12  Type_ID                          921 non-null    int64
 13  Category_ID                      921 non-null    int64
 14  Cuisine_ID                       921 non-null    int64
 15  Working Hrs                      921 non-null    object
 16  Delivery Available               921 non-null    object
 17  Table Booking Available          921 non-null    object
 18  Price                            921 non-null    float64
 19  Discounts Offered (%)            921 non-null    float64
 20  Discounted Price                 921 non-null    float64
 21  Expected Revenue                 921 non-null    float64
 22  Customer ID                      921 non-null    int64
 23  Cust Rating_ID                   921 non-null    int64
 24  Order_Status_ID                  921 non-null    int64
 25  Cancellation_ID                  921 non-null    int64
 26  Actual Revenue                   921 non-null    float64
 27  Operating Cost                   921 non-null    float64
 28  GP Margin                        921 non-null    float64
 29  Total Number of Reviews          921 non-null    int64
 30  Number of Complaints Received    921 non-null    int64
 31  Foot Traffic in Location         921 non-null    object
 32  Competitors in the Area (Count)  921 non-null    int64
 33  Subscription_ID                  921 non-null    int64
 34  Budgetd_Rev                      921 non-null    float64
 35  Budgetd_Operating Cost           921 non-null    float64
 36  Budgeted Order                   921 non-null    float64
 37  Budgeted GP                      921 non-null    float64
 38  Acquisition cost                 921 non-null    float64
 39  Value                            921 non-null    float64
 40  year                             921 non-null    int64
 41  month                            921 non-null    int64
dtypes: float64(13), int64(22), object(7)
memory usage: 302.3+ KB

In [116]:
df.drop(columns=['year','month'],inplace=True)

In [117]:
df.isnull().sum()

Item_ID                            0
Master_Restaurant_Id               0
Date_ID                            0
Time of Order                      0
Order Delivered Date               0
Time of Delivery                   0
Expected Delivery Time             0
Delivery Time (in mins)            0
Restaurant_ID                      0
Desc_ID                            0
Location_ID                        0
Avg Rating_ID                      0
Type_ID                            0
Category_ID                        0
Cuisine_ID                         0
Working Hrs                        0
Delivery Available                 0
Table Booking Available            0
Price                              0
Discounts Offered (%)              0
Discounted Price                   0
Expected Revenue                   0
Customer ID                        0
Cust Rating_ID                     0
Order_Status_ID                    0
Cancellation_ID                    0
Actual Revenue                     0
Operating Cost                     0
GP Margin                          0
Total Number of Reviews            0
Number of Complaints Received      0
Foot Traffic in Location           0
Competitors in the Area (Count)    0
Subscription_ID                    0
Budgetd_Rev                        0
Budgetd_Operating Cost             0
Budgeted Order                     0
Budgeted GP                        0
Acquisition cost                   0
Value                              0
dtype: int64

In [118]:
df.shape

(921, 40)

In [119]:
new_columns = []

for col in df.columns:
    col = col.strip()        # remove leading & trailing spaces
    col = col.lower()        # convert to lowercase
    col = col.replace(' ', '_')  # replace spaces with underscore
    new_columns.append(col)

df.columns = new_columns

In [120]:
df.columns

Index(['item_id', 'master_restaurant_id', 'date_id', 'time_of_order',
       'order_delivered_date', 'time_of_delivery', 'expected_delivery_time',
       'delivery_time_(in_mins)', 'restaurant_id', 'desc_id', 'location_id',
       'avg_rating_id', 'type_id', 'category_id', 'cuisine_id', 'working_hrs',
       'delivery_available', 'table_booking_available', 'price',
       'discounts_offered_(%)', 'discounted_price', 'expected_revenue',
       'customer_id', 'cust_rating_id', 'order_status_id', 'cancellation_id',
       'actual_revenue', 'operating_cost', 'gp_margin',
       'total_number_of_reviews', 'number_of_complaints_received',
       'foot_traffic_in_location', 'competitors_in_the_area_(count)',
       'subscription_id', 'budgetd_rev', 'budgetd_operating_cost',
       'budgeted_order', 'budgeted_gp', 'acquisition_cost', 'value'],
      dtype='object')

In [121]:
df.rename(columns={
    'delivery_time_(in_mins)': 'delivery_time_in_mins',
    'discounts_offered_(%)': 'discounts_offered_pct',
    'average_rating.1': 'average_rating_1',
    'competitors_in_the_area_(count)': 'competitors_in_the_area_count'
}, inplace=True)

In [122]:
df.columns

Index(['item_id', 'master_restaurant_id', 'date_id', 'time_of_order',
       'order_delivered_date', 'time_of_delivery', 'expected_delivery_time',
       'delivery_time_in_mins', 'restaurant_id', 'desc_id', 'location_id',
       'avg_rating_id', 'type_id', 'category_id', 'cuisine_id', 'working_hrs',
       'delivery_available', 'table_booking_available', 'price',
       'discounts_offered_pct', 'discounted_price', 'expected_revenue',
       'customer_id', 'cust_rating_id', 'order_status_id', 'cancellation_id',
       'actual_revenue', 'operating_cost', 'gp_margin',
       'total_number_of_reviews', 'number_of_complaints_received',
       'foot_traffic_in_location', 'competitors_in_the_area_count',
       'subscription_id', 'budgetd_rev', 'budgetd_operating_cost',
       'budgeted_order', 'budgeted_gp', 'acquisition_cost', 'value'],
      dtype='object')

In [123]:
df.duplicated().sum()

np.int64(48)

In [124]:
df = df.drop_duplicates()

In [125]:
df.shape

(873, 40)

# **Fixing Data Types**

In [126]:
df['order_delivered_date'].head()

0    2022-01-01
1    2022-01-01
2    2022-01-01
3    2022-01-01
4    2022-01-01
Name: order_delivered_date, dtype: object

In [127]:
df['order_delivered_date'] = pd.to_datetime(df['order_delivered_date'], format='mixed', errors='coerce')

In [128]:
df['order_delivered_date'].info()

<class 'pandas.core.series.Series'>
Index: 873 entries, 0 to 920
Series name: order_delivered_date
Non-Null Count  Dtype
--------------  -----
873 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 13.6 KB

In [129]:
df[['time_of_order','time_of_delivery']].head()

  time_of_order time_of_delivery
0       5:16:00         19:13:00
1       8:02:00          9:00:00
2      20:34:00          4:19:00
3       5:46:00          6:40:00
4       7:24:00          8:16:00

In [130]:
df[df['time_of_order'] > df['time_of_delivery']].shape[0]

89

In [131]:
import pandas as pd

# ----------------------------
# 1. Convert to timedelta (correct way for string time)
# ----------------------------
for col in ['time_of_order', 'time_of_delivery']:
    df[col] = pd.to_timedelta(df[col]).dt.round('1s')

# ----------------------------
# 2. Remove invalid rows
# ----------------------------
df = df[df['time_of_order'] <= df['time_of_delivery']]

# ----------------------------
# 3. Filter <= 2 hours gap
# ----------------------------
df = df[
    (df['time_of_delivery'] - df['time_of_order']) <= pd.Timedelta(hours=2)
]

# ----------------------------
# 4. Convert to HH:MM:SS (for MySQL)
# ----------------------------
for col in ['time_of_order', 'time_of_delivery']:
    df[col] = df[col].astype(str).str.split().str[-1]

# ----------------------------
# 5. Final check
# ----------------------------
print(df[['time_of_order','time_of_delivery']].head())
print("Final shape:", df.shape)

  time_of_order time_of_delivery
1      08:02:00         09:00:00
3      05:46:00         06:40:00
4      07:24:00         08:16:00
5      16:20:00         16:58:00
6      20:12:00         21:08:00
Final shape: (747, 40)

In [132]:
df.sample(5)

,item_id,master_restaurant_id,date_id,time_of_order,order_delivered_date,time_of_delivery,expected_delivery_time,delivery_time_in_mins,restaurant_id,desc_id,location_id,avg_rating_id,type_id,category_id,cuisine_id,working_hrs,delivery_available,table_booking_available,price,discounts_offered_pct,discounted_price,expected_revenue,customer_id,cust_rating_id,order_status_id,cancellation_id,actual_revenue,operating_cost,gp_margin,total_number_of_reviews,number_of_complaints_received,foot_traffic_in_location,competitors_in_the_area_count,subscription_id,budgetd_rev,budgetd_operating_cost,budgeted_order,budgeted_gp,acquisition_cost,value
231,16,95,371,03:58:06,2022-01-05,04:43:06,53,45,18,18,7,3,3,3,5,11:00AM - 11:00PM,Yes,No,1288.00,22.35,1000.00,1000.00,11,7,2,5,1000.0,750.00,250.00,497,90,Medium,34,2,1130.149160,832.609890,0.0,297.539270,17.117117,287.8680
164,16,95,371,03:58:06,2022-01-05,04:43:06,53,45,18,18,7,3,3,3,5,11:00AM - 11:00PM,Yes,No,1288.00,22.35,1000.00,1000.00,11,7,2,5,1000.0,720.00,280.00,497,90,Medium,34,2,1150.151800,820.908346,0.0,329.243454,13.157895,287.8680
389,11,110,377,18:15:57,2022-01-11,19:00:57,34,45,17,17,15,4,3,4,5,11:00AM - 11:00PM,Yes,No,494.00,3.13,479.00,479.00,15,6,2,5,479.0,383.00,96.00,80,60,Medium,45,3,540.747714,432.598171,0.0,108.149543,13.274336,15.4622
173,6,64,736,19:16:00,2022-01-05,19:51:00,38,35,94,927,16,1,1,10,7,11:00AM - 11:00PM,YES,YES,1035.42,13.09,899.88,899.88,875,1,999,3,0.0,620.91,278.97,78,9,high,24,1,884.770000,663.020000,165.0,221.750000,20.230000,338.3100
156,25,87,370,03:01:18,2022-01-04,03:49:18,53,48,11,11,10,4,1,1,4,"12:00PM - 3:30PM, 7:00PM - 11:30PM",Yes,Yes,523.00,3.34,506.00,506.00,6,5,2,5,506.0,374.00,131.00,254,28,Medium,50,2,581.361570,426.466627,0.0,154.894944,15.789474,17.4682

In [133]:
# ----------------------------
# 1. Create date_id (YYYYMMDD)
# ----------------------------
df['date_id'] = df['order_delivered_date'].dt.strftime('%Y%m%d').astype(int)

# ----------------------------
# 2. Move date_id to first column
# ----------------------------
cols = ['date_id'] + [col for col in df.columns if col != 'date_id']
df = df[cols]
# ----------------------------
# 3. Drop original date column
# ----------------------------
df.drop(columns=['order_delivered_date'], inplace=True)

# ----------------------------
# 4. Check
# ----------------------------
df.head()

,date_id,item_id,master_restaurant_id,time_of_order,time_of_delivery,expected_delivery_time,delivery_time_in_mins,restaurant_id,desc_id,location_id,avg_rating_id,type_id,category_id,cuisine_id,working_hrs,delivery_available,table_booking_available,price,discounts_offered_pct,discounted_price,expected_revenue,customer_id,cust_rating_id,order_status_id,cancellation_id,actual_revenue,operating_cost,gp_margin,total_number_of_reviews,number_of_complaints_received,foot_traffic_in_location,competitors_in_the_area_count,subscription_id,budgetd_rev,budgetd_operating_cost,budgeted_order,budgeted_gp,acquisition_cost,value
1,20220101,6,70,08:02:00,09:00:00,49,58,78,956,1,2,1,8,5,11:00AM - 11:00PM,YES,YES,1055.34,12.95,918.67,918.67,3029,1,999,4,0.00,596.63,322.04,23,11,low,6,3,908.62,650.31,187.0,258.31,14.30,349.29
3,20220101,6,64,05:46:00,06:40:00,51,54,36,948,16,4,1,3,2,11:00AM - 11:00PM,YES,YES,1192.89,11.31,1057.97,1057.97,861,5,999,5,1057.97,842.00,215.97,46,15,medium,17,1,1116.96,828.12,291.0,288.84,21.70,253.64
4,20220101,6,68,07:24:00,08:16:00,47,52,74,938,5,1,1,6,10,11:00AM - 11:00PM,YES,YES,592.40,22.44,459.47,459.47,3144,4,999,3,0.00,341.39,118.08,197,12,high,15,1,467.62,355.01,275.0,112.61,10.09,217.00
5,20220101,6,64,16:20:00,16:58:00,46,38,74,968,16,5,1,1,7,11:00AM - 11:00PM,YES,YES,628.64,6.20,589.66,589.66,672,5,999,5,589.66,399.97,189.69,162,12,low,10,2,575.64,414.67,156.0,160.97,18.83,226.41
6,20220101,6,67,20:12:00,21:08:00,52,56,97,983,1,7,1,7,4,11:00AM - 11:00PM,YES,YES,236.16,25.91,174.97,174.97,820,5,999,5,174.97,110.43,64.54,59,5,low,12,1,166.44,106.91,252.0,59.53,22.13,155.09

In [134]:
# now save this data to current_clean_data folder overwrite old data

import os

file_path = "clean_data.csv"

# Save and overwrite
df.to_csv(file_path, index=False)

print(f"✅ Data saved successfully at: {file_path}")

✅ Data saved successfully at: clean_data.csv

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 747 entries, 1 to 920
Data columns (total 39 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date_id                        747 non-null    int64
 1   item_id                        747 non-null    int64
 2   master_restaurant_id           747 non-null    int64
 3   time_of_order                  747 non-null    object
 4   time_of_delivery               747 non-null    object
 5   expected_delivery_time         747 non-null    int64
 6   delivery_time_in_mins          747 non-null    int64
 7   restaurant_id                  747 non-null    int64
 8   desc_id                        747 non-null    int64
 9   location_id                    747 non-null    int64
 10  avg_rating_id                  747 non-null    int64
 11  type_id                        747 non-null    int64
 12  category_id                    747 non-null    int64
 13  cuisine_id                     747 non-null    int64
 14  working_hrs                    747 non-null    object
 15  delivery_available             747 non-null    object
 16  table_booking_available        747 non-null    object
 17  price                          747 non-null    float64
 18  discounts_offered_pct          747 non-null    float64
 19  discounted_price               747 non-null    float64
 20  expected_revenue               747 non-null    float64
 21  customer_id                    747 non-null    int64
 22  cust_rating_id                 747 non-null    int64
 23  order_status_id                747 non-null    int64
 24  cancellation_id                747 non-null    int64
 25  actual_revenue                 747 non-null    float64
 26  operating_cost                 747 non-null    float64
 27  gp_margin                      747 non-null    float64
 28  total_number_of_reviews        747 non-null    int64
 29  number_of_complaints_received  747 non-null    int64
 30  foot_traffic_in_location       747 non-null    object
 31  competitors_in_the_area_count  747 non-null    int64
 32  subscription_id                747 non-null    int64
 33  budgetd_rev                    747 non-null    float64
 34  budgetd_operating_cost         747 non-null    float64
 35  budgeted_order                 747 non-null    float64
 36  budgeted_gp                    747 non-null    float64
 37  acquisition_cost               747 non-null    float64
 38  value                          747 non-null    float64
dtypes: float64(13), int64(20), object(6)
memory usage: 233.4+ KB